# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

org.gradle.configuration-cache=false

# Fabric Properties
minecraft_min_version=26.1
minecraft_max_version=26.1.2
minecraft_version=26.1
fabric_loader_version=0.18.4
loom_version=1.15-SNAPSHOT

# Mod Properties
mod_id=logic_gate
mod_name=Logic Gate
mod_version=1.0.1-26.1-26.1.1
mod_license=MIT License
mod_authors=Duppy Conqueror
mod_description=All-in-one, toggleable logic gate as a redstone component.
mod_github=https://github.com/Duppy-Conqueror/LogicGate
mod_issues=https://github.com/Duppy-Conqueror/LogicGate/issues
maven_group=net.duppy_conqueror.logic_gate
archives_base_name=logic_gate

# Dependencies
fabric_api_version=0.145.4+26.1.2

cloth_config_api_version=26.1.154
modmenu_version=18.0.0-alpha.8
yacl_version=3.9.2+26.1-fabric