# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

org.gradle.configuration-cache=false

# Fabric Properties
minecraft_min_version=26.2
minecraft_max_version=26.2
minecraft_version=26.2
minecraft_version_range=[26.2]

# Neoforge Properties
neoforge_version=26.2.0.72

# Mod Properties
mod_id=logic_gate
mod_name=Logic Gate
mod_version=1.0.3+26.2-neoforge
mod_license=MIT License
mod_authors=Duppy Conqueror
mod_description=All-in-one, toggleable logic gate as a redstone component.
mod_github=https://github.com/Duppy-Conqueror/LogicGate
mod_issues=https://github.com/Duppy-Conqueror/LogicGate/issues
mod_group_id=net.duppy_conqueror.logic_gate
archives_base_name=logic_gate

# Dependencies
cloth_config_api_version=26.2.155
yacl_version=3.9.6+26.2-neoforge