# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
minecraft_min_version=1.21.9
minecraft_max_version=1.21.10
minecraft_version=1.21.10
yarn_mappings=1.21.10+build.3
fabric_loader_version=0.18.4
loom_version=1.15-SNAPSHOT

# Mod Properties
mod_id=logic_gate
mod_name=Logic Gate
mod_version=0.4.0-1.21.9-1.21.10
mod_license=MIT License
mod_authors=Duppy Conqueror
mod_description=All-in-one, toggleable logic gate as a redstone component.
mod_github=https://github.com/Duppy-Conqueror/LogicGate
mod_issues=https://github.com/Duppy-Conqueror/LogicGate/issues
maven_group=net.duppy_conqueror.logic_gate
archives_base_name=logic_gate

# Dependencies
fabric_api_version=0.138.4+1.21.10

cloth_config_api_version=20.0.149
modmenu_version=16.0.0
yacl_version=3.8.2+1.21.10-fabric